services:
  frontend:
    build:
      context: ./credere-frontend/
      args:
        max_size_body: ${VITE_MAX_FILE_SIZE_MB}
    environment:
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_HOST=${VITE_HOST}
      - VITE_TRANSIFEX_TOKEN=${VITE_TRANSIFEX_TOKEN}
      - VITE_DEFAULT_LANG=${VITE_DEFAULT_LANG}
      - VITE_CREDERE_PHONE_NUMBER=${VITE_CREDERE_PHONE_NUMBER}
      - VITE_LOCALE=${VITE_LOCALE}
      - VITE_CURRENCY=${VITE_CURRENCY}
      - VITE_MORE_INFO_OCP_URL=${VITE_MORE_INFO_OCP_URL}
      - VITE_MAX_FILE_SIZE_MB=${VITE_MAX_FILE_SIZE_MB}

    ports:
      - '8000:80'
  backend:
    build: ./credere-backend/
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_CLIENT_SECRET=${AWS_CLIENT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - COGNITO_POOL_ID=${COGNITO_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - FRONTEND_URL=${FRONTEND_URL}
      - COLOMBIA_SECOP_APP_TOKEN=${COLOMBIA_SECOP_APP_TOKEN}
      - SECOP_PAGINATION_LIMIT=${SECOP_PAGINATION_LIMIT}
      - HASH_KEY=${HASH_KEY}
      - TEST_MAIL_RECEIVER=${TEST_MAIL_RECEIVER}
      - IMAGES_BASE_URL=${IMAGES_BASE_URL}
      - EMAIL_TEMPLATE_LANG=${EMAIL_TEMPLATE_LANG}
      - FACEBOOK_LINK=${FACEBOOK_LINK}
      - TWITTER_LINK=${TWITTER_LINK}
      - LINK_LINK=${LINK_LINK}
      - OCP_EMAIL_GROUP=${OCP_EMAIL_GROUP}
      - APPLICATION_EXPIRATION_DAYS=${APPLICATION_EXPIRATION_DAYS}
      - DAYS_TO_CHANGE_TO_LAPSED=${DAYS_TO_CHANGE_TO_LAPSED}
      - DAYS_TO_ERASE_BORROWERS_DATA=${DAYS_TO_ERASE_BORROWERS_DATA}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}
      - REMINDER_DAYS_BEFORE_EXPIRATION=${REMINDER_DAYS_BEFORE_EXPIRATION}
      - PROGRESS_TO_REMIND_STARTED_APPLICATIONS=${PROGRESS_TO_REMIND_STARTED_APPLICATIONS}
      - ENVIRONMENT=${ENVIRONMENT}

    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:8000'
