services:
  frontend:
    build: .
    environment:
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_HOST=${VITE_HOST}
      - VITE_TRANSIFEX_TOKEN=${VITE_TRANSIFEX_TOKEN}
      - VITE_DEFAULT_LANG=${VITE_DEFAULT_LANG}
      - VITE_CREDERE_PHONE_NUMBER=${VITE_CREDERE_PHONE_NUMBER}
    ports:
      - '80:80'
  backend:
    build: ../credere-backend/
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_CLIENT_SECRET=${AWS_CLIENT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - COGNITO_POOL_ID=${COGNITO_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - FRONTEND_URL=${FRONTEND_URL}
      - COLOMBIA_SECOP_APP_TOKEN=${COLOMBIA_SECOP_APP_TOKEN}
      - SECOP_PAGINATION_LIMIT=${SECOP_PAGINATION_LIMIT}
      - HASH_KEY=${HASH_KEY}
      - TEST_MAIL_RECEIVER=${TEST_MAIL_RECEIVER}
      - FRONT_PUBLIC_IMAGES_ES=${FRONT_PUBLIC_IMAGES_ES}
      - FRONT_PUBLIC_IMAGES_EN=${FRONT_PUBLIC_IMAGES_EN}
      - FACEBOOK_LINK=${FACEBOOK_LINK}
      - TWITTER_LINK=${TWITTER_LINK}
      - LINK_LINK=${LINK_LINK}
      - TEMPORAL_BUCKET=${TEMPORAL_BUCKET}
    ports:
      - '8000:8000'
