name: Deploy
on:
  workflow_run:
    workflows: ["Lint JavaScript"]  # Change to "CI" once tests added
    branches: [main]
    types:
      - completed
jobs:
  docker:
    uses: open-contracting/.github/.github/workflows/docker-single.yml@main
